#docker-compose version
version: "3"
services:
  mysql-standalone:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=test
  user-web-app:
    #Build the image using the docker file which is in the current folder
    build: .
    ports:
      - "8083:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql-standalone:3306/test?autoReconnect=true&useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root123",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - mysql-standalone